### ISSUE TITLE
gcmon stops emitting GC events if a 2nd gcmon is used to monitor the first

### ISSUE THREAD

**Issue by ryandle** [Maoni0/realmon#25]
1. Open admin console
2. Run gcmon on a process `dotnet gcmon -n <processName>`
2. Observe that it is emitting GC events / works as expected.
3. Open a 2nd admin console
4. Run a 2nd gcmon instance to monitor the first `dotnet gcmon -p <pidOfFirstGcMonProcess>`

**_Expected_**: The first gcmon process continues to work as expected and the second one reports on the 1st's GC behavior.

**_Actual_**: The first gcmon appears to stop writing gc events to the output once the 2nd starts monitoring it.

I've been able to repro this on Windows 10 20H2. Haven't tried any other platforms.

**Comment by MokoSan** [comment]
Could this be because the name of the session is hardcoded as ``MySession`` [here](https://github.com/Maoni0/realmon/blob/6e311b5c78a7f0529d4c36e97904ad10ef47bbf8/src/GCRealTimeMon/Utilities/PlatformUtilities.cs#L18) and we are opening multiple of these sessions, which seems like a violation of what's described in the TraceProgrammer's Guide in [this](https://github.com/microsoft/perfview/blob/main/documentation/TraceEvent/TraceEventProgrammersGuide.md#component-2-the-event-session-traceeventsession) section:

> "Creates a new TraceEventSession, each session is given a name that is unique ACROSS THE MACHINE. In our case we called our session MySession. Sessions CAN live beyond the lifetime of process that created them, and this name is how you refer to these sessions from other processes besides the process that created them. We also specify a file where the data is to be logged. By convention, these data files use the .ETL (Event Trace Log) suffix."

__Solution__: Pass in a forced unique session name via a command line argument.

**Comment by Maoni0** [comment]
@MokoSan that certainly sounds like a plausible cause :)

**Comment by MokoSan** [comment]
Just proved that my hypothesis is true.. Will add a new command line arg for specifying the name of the session.

**Comment by ryandle** [comment]
If the arg is not passed by the user, could the session name be random (a
guid?) to avoid collision? My reasoning is: As a user, I don’t want to have
to remember to use an extra argument if I’m running more than one gcmon
instance.

**Comment by MokoSan** [comment]
Yup - my alternative solution was exactly along those lines.. A guid based name of a session was what I was going for. More I think about this, the more I agree with your rationale - as it is, we have enough command line args. Thanks!
